
windowWidth: 1920
windowHeight: 1080
# windowWidth: 1200
# windowHeight: 900
fov: 75
serverAddress: "127.0.0.1"
droneName: "Wojtek"
defaultCamera: "HorizontalCamera"
joystick:
  deadZoneFactor: 0.2
  mappings:
    buttonActions:
      0: "noneMode"
      1: "acroMode"
      3: "angleMode"
      4: "posMode"
      6: "nextCamera"
      7: "prevCamera"
    axisActions:
      4: "shoot"
    axes:
      5: "rotation"
      2: "heightChange"
      0: "sidewaysMovement"
      1: "straightMovement"
    axisInversions:
      5: false
      2: true
      0: false
      1: true
ports:
  droneRequester: 9000
  droneStatuses: 9090
  projectileStatuses: 9100
heartBeatIntervalMs: 500
