serverSettings:
  serverAddress: 127.0.0.1
  assetsSourceUrl: https://github.com/MiNI-UAV/UAV_aggregator/releases/download/
  downloadMissingAssets: true
  # assetsToUse: f7a4510e # Comment out if above is true.
  heartBeatIntervalMs: 500
  serverTimoutMs: 5000
droneSettings:
  droneName: Maurice
  droneModel: quadcopter
  defaultCamera: HorizontalCamera
  defaultControlMode: Positional # Only GUI
sceneSettings:
  drawInWorldDemandedPositionalCoords: true
  sunAngleDayCycle: -20 # -45 Sunrise, 45 Sunset
  sunAngleYearCycle: 70 # 15 Winter, 60 Summer (90 is not allowed)
graphicsSettings:
  windowWidth: 1920
  windowHeight: 1080
  fullScreenMode: Window
  monitor: 0
  guiScale: 1
  fov: 100 # 0 < fov < 180
  useGammaCorrection: true
  gammaCorrection: 2.2
  useShadows: true
  shadowsTextureResolution: 6072
  shadowsRenderingDistance: 300
joystick:
  deadZoneFactor: 0.1
  mappings:
    buttonActions:
      0: noneMode
      1: acroMode
      2: unused
      3: angleMode
      4: posMode
      5: unused
      6: nextCamera
      7: prevCamera
      8: unused
      9: unused
      10: unused
      11: unused
      12: unused
      13: respawn
      14: unused
    axisActions:
      4: shoot
      5: drop
    axes:
      0: rotation
      1: heightChange
      2: sidewaysMovement
      3: straightMovement
    axisInversions:
      0: false
      1: true
      2: false
      3: true
ports:
  notifications: 8000
  droneRequester: 9000
  droneStatuses: 9090
  projectileStatuses: 9100
