bindingsConfig: bindings.yaml
serverSettings:
  serverAddress: 127.0.0.1
  assetsSourceUrl: https://github.com/MiNI-UAV/UAV_aggregator/releases/download/
  downloadMissingAssets: true
  #assetsToUse: f7a4510e # Comment out if above is true.
  heartBeatIntervalMs: 500
  serverTimoutMs: 5000
droneSettings:
  droneName: Maurice
  droneModel: quadcopter
  defaultCamera: HorizontalCamera
  modes:
    - QPOS
    - QANGLE
    - QACRO
#    - FMANUAL
#    - RMANUAL
sceneSettings:
  drawInWorldDemandedPositionalCoords: true
  sunAngleDayCycle: 38 # -45 Sunrise, 45 Sunset
  sunAngleYearCycle: 124 # 15 Winter, 60 Summer (90 is not allowed)
graphicsSettings:
  windowWidth: 1920
  windowHeight: 1080
  fullScreenMode: FullScreen
  monitor: 0
  guiScale: 1
  fov: 100 # 0 < fov < 180
  useGammaCorrection: true
  gammaCorrection: 2.2
  useShadows: true # TODO: Unused
  shadowsTextureResolution: 6072
  shadowsRenderingDistance: 300
ports:
  notifications: 8000
  droneRequester: 9000
  droneStatuses: 9090
  projectileStatuses: 9100
