name: Bundling app for windows and linux
run-name: bundle
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: '0'
      - name: Put tag
        run: |
          version=`gradle -q printVersion`
          name=mini-uav-$version
          if ! [ $(git tag -l "$name") ]; then
            tar -czf assets.tar.gz assets
            git tag "${name}"
            git push origin --tags
            echo "TAG_NAME=${name}" >> "$GITHUB_ENV"
          fi
      - name: Release assets
        if: env.TAG_NAME
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG_NAME }}
          artifacts: build/mini-uav/mini-uav-${{ env.TAG_NAME }}.tar.gz